services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: findById-anti-pattern
    volumes:
      - database_volume:/var/lib/postgres/data
    ports:
      - "5432:5432"

volumes:
  database_volume: